### PR TITLE
Add API to register server

### PR DESCRIPTION
**Pull request by IamTaoChen**
## Summary
1. add 1 POST endpoints `/api/v1/server/register`
2. add `docker-compose.yml` and `Dockerfile.dev` for developing

#### `/api/v1/server/register`

POST data format
```json
{
  "name": "abcd",
  "Tag": "",
  "Note": "",
  "HideForGuest": "on"
}
```
You can post a empty data `{}`, then it will use the default data
```
name=$IP
Tag="AutoRegister"
Note=""
HideForGuest="on"
```
If it contain query `simple=1` or `simple=true`, it will only return a secret string. Otherwise It return json
```json
{
"code":200,
"message":"Server created successfully",
"secret":"8GYwaxYuLfU7zl7ndC"
}
```

## Example

1. without `simple`

```bash
➜  ~ curl -X POST http://127.0.0.1:18080/api/v1/server/register \ 
  -H "Content-Type: application/json" \
  -H "Authorization: POXbxorKJBM8wPMKX8r2PdMblyXvpggB" \
  -d '{
    "name": "curl",
    "Tag": "",
    "Note": "",
    "HideForGuest": "on"
  }'
{"code":200,"message":"Server created successfully","secret":"XQ2HsGWRQvcVCBPWXh"}
```

2. with `simple=1`

 ```bash
➜  ~ curl -X POST http://127.0.0.1:18080/api/v1/server/register?simple=1 \
  -H "Content-Type: application/json" \
  -H "Authorization: POXbxorKJBM8wPMKX8r2PdMblyXvpggB" \
  -d '{
    "name": "curl",
    "Tag": "",
    "Note": "",
    "HideForGuest": "on"
  }'
"gv4eGLwyvHIR9y5E7p"
```

### CODE REVIEW

**Comment by IamTaoChen** [comment]
example
```bash
#!/bin/bash

# Exit if NEZHA_TOKEN is not set
if [ -z "${NEZHA_TOKEN}" ]; then
    echo "NEZHA_TOKEN is not set. Exiting."
    exit 0
fi

# Set default values if variables are not set
PROBE_ADDRESS="${PROBE_ADDRESS:-probe.example.com}"
PROBE_PORT="${PROBE_PORT:-5555}"
NEZHA_DASHBOARD_URL="https://nezha.example.com"

HOSTNAME=$(hostname)

# Send POST request and capture response and HTTP status code
response=$(curl -s -o response_body.json -w "%{http_code}" -X POST "${NEZHA_DASHBOARD_URL}/api/v1/server/register2" \
  -H "Content-Type: application/json" \
  -H "Authorization: ${NEZHA_TOKEN}" \
  -d "{\"name\": \"${HOSTNAME}\"}")

# Extract HTTP status code and Nezha secret
HTTP_CODE="$response"
NEZHA_SECRET=$(cat response_body.json)
rm -f response_body.json

if [ "$HTTP_CODE" != "200" ]; then
    echo "Failed to get Nezha Secret. HTTP status code: $HTTP_CODE"
    exit 1
fi

# Additional check for NEZHA_SECRET to ensure it's not JSON-formatted (indicating failure)
if [[ "${NEZHA_SECRET:0:1}" == "{" ]]; then
    echo "Failed to get Nezha Secret. Received response: ${NEZHA_SECRET}"
    exit 1
fi

# Download and execute the install script with cleanup
curl -fsSL https://raw.githubusercontent.com/naiba/nezha/master/script/install_en.sh -o nezha.sh && \
chmod +x nezha.sh || { echo "Failed to download or make the script executable"; exit 1; }

# Clean up nezha.sh on exit
trap 'rm -f nezha.sh' EXIT

# Run the Nezha agent installation script with the retrieved secret
./nezha.sh install_agent "${PROBE_ADDRESS}" "${PROBE_PORT}" "${NEZHA_SECRET}" --tls
# Run the Nezha agent installation script
CMD="./nezha.sh install_agent "${PROBE_ADDRESS}" "${PROBE_PORT}" "${NEZHA_SECRET}" --tls"

echo "Run commnad : ${CMD}"

eval $CMD
```

**Comment by naiba** [comment]
可以放到query里，不需要两个接口

**Comment by IamTaoChen** [comment]
> 可以放到query里，不需要两个接口

updated

**Comment by hiDandelion** [comment]
Hi. Could you explain why `name`, `Tag`, `Note`, `HideForGuest` in the request body have different capitalization rules?

**Comment by IamTaoChen** [comment]
> Hi. Could you explain why `name`, `Tag`, `Note`, `HideForGuest` in the request body have different capitalization rules?

Hi, sorry this is my fault. I didn't notice that, but both 'name' and 'Name' work. And do you think I should format this form, like 

```json
{
"name": "name1",
"tag" : "tag",
"note" : "note",
"hide_for_guest": "on"
}
```

**Comment by hiDandelion** [comment]
> > Hi. Could you explain why `name`, `Tag`, `Note`, `HideForGuest` in the request body have different capitalization rules?
> 
> Hi, sorry this is my fault. I didn't notice that, but both 'name' and 'Name' work. And do you think I should format this form, like
> 
> ```json
> {
> "name": "name1",
> "tag" : "tag",
> "note" : "note",
> "hide_for_guest": "on"
> }
> ```

Thank you for clarification. I just want to make sure this is not a mistake to be fixed in near future. Since the new version has been released, maybe it is not the right time to change it now.

**Pull request merged**
